---
abstract: 'Save google charts to images using phantomjs'
author:
  - 'Simon Elliott <simon@papercreatures.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wight-Chart-Google
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Wight::Chart::Google:
    file: lib/Wight/Chart/Google.pm
    version: 0.001
requires:
  Cwd: 0
  File::Share: 0
  JSON::XS: 0
  Moo: 0
  Template::Tiny: 0
  Wight: 0
  perl: 5.006
  strictures: 1
resources:
  bugtracker: https://github.com/papercreatures/wight-chart-google/issues
  homepage: https://metacpan.org/release/Wight-Chart-Google
  repository: git://github.com/papercreatures/wight-chart-google.git
version: 0.001
